#pragma once
#include <windows.h>
#include "tp_gadget.h"
#include "internals.h"

#define STATUS_SUCCESS  ((NTSTATUS)0x00000000L)

HMODULE H_LoadLibraryA(LPCSTR);
NTSTATUS H_NtOpenProcess(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, PCLIENT_ID);
NTSTATUS H_NtAllocateVirtualMemory(HANDLE, PVOID *, ULONG_PTR, PSIZE_T, ULONG, ULONG);
NTSTATUS H_NtWriteVirtualMemory(HANDLE, PVOID, PVOID, SIZE_T, PSIZE_T);
NTSTATUS H_NtProtectVirtualMemory(HANDLE, PVOID *, PSIZE_T, ULONG, PULONG);
NTSTATUS H_NtFreeVirtualMemory(HANDLE, PVOID *, PSIZE_T, ULONG);
NTSTATUS H_NtClose(HANDLE);
NTSTATUS H_NtCreateThreadEx(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, HANDLE, PUSER_THREAD_START_ROUTINE, PVOID, ULONG, SIZE_T, SIZE_T, SIZE_T, PPS_ATTRIBUTE_LIST);
NTSTATUS H_NtOpenThread (PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, PCLIENT_ID);
NTSTATUS H_NtSuspendThread (HANDLE, PULONG);
NTSTATUS H_NtResumeThread (HANDLE, PULONG);
NTSTATUS H_NtGetContextThread(HANDLE, PCONTEXT);
NTSTATUS H_NtSetContextThread(HANDLE, PCONTEXT);
NTSTATUS H_NtWaitForSingleObject (HANDLE, BOOLEAN, PLARGE_INTEGER);
